disable-version-string: true
with-expecter: true
mockname: 'Mock{{.InterfaceName | camelcase}}'
filename: '{{.InterfaceName | camelcase | firstLower}}.go'
outpkg: '{{.PackageName}}'
dir: 'internal/generated/mocks/{{replaceAll .PackagePath "github.com/nijeti/cinema-keeper/internal" ""}}'
packages:
  github.com/nijeti/healthcheck:
    config:
      recursive: true
      include-regex: '.*'
      exclude-regex: 'Option'
