name: 'Validate'

on:
  pull_request:
    branches:
      - 'main'
    paths:
      - '.github/**'
      - 'servers/**'
      - '.golangci.yaml'
      - '*.go'
      - 'go.*'

env:
  HTTP_SERVER: './servers/http/'
  FASTHTTP_SERVER: './servers/fasthttp/'

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: read

    steps:
      - name: 'Checkout'
        uses: actions/checkout@v4

      - name: 'Setup Go'
        uses: actions/setup-go@v5
        with:
          go-version-file: 'go.mod'

      - name: 'Build package'
        run: go build ./

      - name: 'Build http server'
        run: go build ${{ env.HTTP_SERVER }}

      - name: 'Build fasthttp server'
        run: go build ${{ env.FASTHTTP_SERVER }}

  prelint:
    runs-on: ubuntu-latest
    
    permissions:
      contents: read
    
    outputs:
      modules: ${{ steps.set-modules.outputs.modules }}
    
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v4

      - name: 'Detect modules'
        id: set-modules
        run: echo "modules=$(go list -m -json | jq -s '.' | jq -c '[.[].Dir]')" >> $GITHUB_OUTPUT

  lint:
    runs-on: ubuntu-latest
    
    needs: prelint
    
    permissions:
      contents: read

    strategy:
      matrix:
        modules: ${{ fromJSON(needs.prelint.outputs.modules) }}
    
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v4

      - name: 'Run linters'
        uses: golangci/golangci-lint-action@v8
        with:
          args: --timeout=2m

  test:
    runs-on: ubuntu-latest
    
    permissions:
      contents: read
    
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v4

      - name: 'Setup Go'
        uses: actions/setup-go@v5
        with:
          go-version-file: 'go.mod'

      - name: 'Test'
        run: ./scripts/test.sh

      - name: 'Upload coverage result'
        uses: coverallsapp/github-action@v2
        with:
          github-token: ${{ github.token }}
          file: coverage.out
          format: golang
